import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

import {
  faSignal,
  faBolt,
  faArrowRight,
  faChevronDown,
  faWifi,
  faBatteryFull,
  faMobileAlt,
  faBoxOpen,
  faStar,
  faCheck,
  faTv,
  faPlayCircle,
  faShieldAlt,
  faHeadset,
  faGlobeAmericas,
  faGift,
  faClock,
  faTachometerAlt,
  faMapMarkerAlt,
  faTrophy,
  faUsers,
  faBroadcastTower,
  faSatelliteDish,
  faMap,
  faPlus,
  faMinus,
  faPhoneAlt,
  faCommentDots,
  faEnvelope,
  faStore,
  faPaperPlane,
  faThumbsUp,
  faComment,
  faCamera,
  faPlay,
  faBuilding,
  faArrowAltCircleLeft,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faSignal,
  faBolt,
  faArrowRight,
  faChevronDown,
  faWifi,
  faBatteryFull,
  faMobileAlt,
  faBoxOpen,
  faStar,
  faCheck,
  faTv,
  faPlayCircle,
  faShieldAlt,
  faHeadset,
  faGlobeAmericas,
  faGift,
  faClock,
  faTachometerAlt,
  faMapMarkerAlt,
  faTrophy,
  faUsers,
  faBroadcastTower,
  faSatelliteDish,
  faMap,
  faPlus,
  faMinus,
  faPhoneAlt,
  faCommentDots,
  faEnvelope,
  faStore,
  faPaperPlane,
  faThumbsUp,
  faComment,
  faCamera,
  faPlay,
  faBuilding,
  faArrowAltCircleLeft,
);

export default FontAwesomeIcon;
